### ISSUE TITLE
still high memory usage and consuption

### ISSUE THREAD

**Issue by areytechai** [dme-compunet/YoloSharp#73] opened 2024-09-28 18:02 UTC
![Screenshot_38](https://github.com/user-attachments/assets/2564100f-bda3-4d19-8961-a9ed705e67ae)
![Screenshot_39](https://github.com/user-attachments/assets/e433cd19-8059-4c19-9be2-50d52afcc49b)

Title: High Memory Usage in PredictorPlottingExtensions Class

Description: I’m experiencing significant memory usage when using the PredictorPlottingExtensions class in the YOLOv8 project. During image processing, memory consumption increases rapidly, leading to performance issues, especially with large images.

Steps to Reproduce:

Use methods like PoseAndSave, DetectAndSave, DetectObbAndSave, SegmentAndSave, or ClassifyAndSave for image processing and saving.
Observe memory usage as the application runs.
Expected Behavior: Memory consumption should remain stable and efficient during image processing and saving.

Actual Behavior: Memory usage increases significantly and doesn't seem to be released, potentially indicating a memory leak or inefficient memory management.

**Comment by areytechai** [comment] 2024-09-28 18:03
[]single i couldnt stop  Single[]	99	457184344	457184344

**Comment by dme-compunet** [comment] 2024-09-29 14:55
It was fixed in version 5.0.2, which version are you using?

**Comment by areytechai** [comment] 2024-09-30 09:05
> It was fixed in version 5.0.2, which version are you using?

The latest version, 5.04,

![image](https://github.com/user-attachments/assets/19764c00-de30-4864-b51e-58d21f561b1b)
after a while

![image](https://github.com/user-attachments/assets/aebfc570-ddca-4400-b939-1ed42afa8378)

  private static string CreateImageOutputPath(string path, YoloTask task)
  {
      var baseDirectory = Path.GetDirectoryName(path) ?? Environment.CurrentDirectory;

      var plotDirectory = Path.Combine(baseDirectory, task.ToString().ToLower());

      if (Directory.Exists(plotDirectory) == false)
      {
          Directory.CreateDirectory(plotDirectory);
      }

      var extn = Path.GetExtension(path);
      var name = Path.GetFileNameWithoutExtension(path);

      var index = 0;

      while (true)
      {
          var filename = index == 0 ? $"{name}{extn}" : $"{name}_{index}{extn}";
          var fullpath = Path.Combine(plotDirectory, filename);
          return fullpath;

          //if (File.Exists(fullpath))
          //{
          //    index++;
          //}
          //else
          //{
          //    return fullpath;
          //}
      }
  }

i try to replace alltime with same file isit cause of it?

single[] is extremly high

**Comment by areytechai** [comment] 2024-09-30 09:28
![image](https://github.com/user-attachments/assets/5cbb7621-cabb-4232-b1af-81cd9e3bf27c)

![image](https://github.com/user-attachments/assets/7a46f806-5f8d-4521-b630-37add636a090)

the single[] class unstopable

![image](https://github.com/user-attachments/assets/a153368c-11de-4f30-accb-139648d8fe25)

**Comment by dme-compunet** [comment] 2024-10-01 08:32
According to the memory graph it seems that there is no leak, but the memory is quite high, and this is possible if you load a large model or several models at the same time, How much does the model you use weigh?

**Comment by areytechai** [comment] 2024-10-01 11:25
just one image progressing, in 3-4 seconds
only segmentation, i just make timer, after 60 minutes restart apps and free the memmory,

any alternative way to clear single[] ?

**Comment by kbank14** [comment] 2024-10-08 09:33
Modify the SerssionRunnerService.cs file

orignal:
        // Bind tensor buffer to ort binding
        binding.BindOutput(session.OutputNames[0], CreateOrtValue(output0.Tensor.Buffer, output0Info.Dimensions64));

       and
            // Bind tensor buffer to ort binding
            binding.BindOutput(session.OutputNames[1], CreateOrtValue(output1.Tensor.Buffer, output1Info.Value.Dimensions64));


change to:
        // Bind tensor buffer to ort binding
        using var ortValue = CreateOrtValue(output0.Tensor.Buffer, output0Info.Dimensions64);
        binding.BindOutput(session.OutputNames[0], ortValue);

      and
         // Bind tensor buffer to ort binding
         using var ortValue1 = CreateOrtValue(output1.Tensor.Buffer, output1Info.Value.Dimensions64);
         binding.BindOutput(session.OutputNames[1], ortValue1);

**Comment by areytechai** [comment] 2024-10-08 11:38
> Modify the SerssionRunnerService.cs file
> 
> orignal: // Bind tensor buffer to ort binding binding.BindOutput(session.OutputNames[0], CreateOrtValue(output0.Tensor.Buffer, output0Info.Dimensions64));
> 
> ```
>    and
>         // Bind tensor buffer to ort binding
>         binding.BindOutput(session.OutputNames[1], CreateOrtValue(output1.Tensor.Buffer, output1Info.Value.Dimensions64));
> ```
> 
> change to: // Bind tensor buffer to ort binding using var ortValue = CreateOrtValue(output0.Tensor.Buffer, output0Info.Dimensions64); binding.BindOutput(session.OutputNames[0], ortValue);
> 
> ```
>   and
>      // Bind tensor buffer to ort binding
>      using var ortValue1 = CreateOrtValue(output1.Tensor.Buffer, output1Info.Value.Dimensions64);
>      binding.BindOutput(session.OutputNames[1], ortValue1);
> ```

Thank you for your message,
i made the changes

i just check the ram status, every minutes its keep growing 

![image](https://github.com/user-attachments/assets/205e9e53-2f33-468c-b12f-e3cfb7e1eefe)

**Comment by areytechai** [comment] 2024-10-08 19:56
> Modify the SerssionRunnerService.cs file
> 
> orignal: // Bind tensor buffer to ort binding binding.BindOutput(session.OutputNames[0], CreateOrtValue(output0.Tensor.Buffer, output0Info.Dimensions64));
> 
> ```
>    and
>         // Bind tensor buffer to ort binding
>         binding.BindOutput(session.OutputNames[1], CreateOrtValue(output1.Tensor.Buffer, output1Info.Value.Dimensions64));
> ```
> 
> change to: // Bind tensor buffer to ort binding using var ortValue = CreateOrtValue(output0.Tensor.Buffer, output0Info.Dimensions64); binding.BindOutput(session.OutputNames[0], ortValue);
> 
> ```
>   and
>      // Bind tensor buffer to ort binding
>      using var ortValue1 = CreateOrtValue(output1.Tensor.Buffer, output1Info.Value.Dimensions64);
>      binding.BindOutput(session.OutputNames[1], ortValue1);
> ```

after 400 minutes run,

![Screenshot 2024-10-08 at 22 55 50](https://github.com/user-attachments/assets/bfcb4cd1-ea91-4c05-8a51-a48fe6bdf463)


this is how much takes memmory the Single[]

**Comment by dme-compunet** [comment] 2024-10-09 07:58
Can you answer some questions?
1. What is the size of your model in disk?
2. What is the size of the input images?
3. Do you see an increase in memory over time, or is it high from the start

**Comment by areytechai** [comment] 2024-10-22 07:33
> Can you answer some questions?
> 
> 1. What is the size of your model in disk?
> 2. What is the size of the input images?
> 3. Do you see an increase in memory over time, or is it high from the start

1-model is standart segmentation model
2 - http://94.124.210.59:8083/mjpg/video.mjpg around 150 kb per image, i make download as jpg and make it progress total size 1024x720 around size
3- yes, i made all achanges, so its growing rapidly and not able to clear current things, the single[] things takes aloooot memmory which i shared images, if there is a way to clear single[] on mmemmory it gona be very nice

**Comment by dme-compunet** [comment] 2024-10-27 11:01
I can't reproduce the issue on my side, so try to create a minimal project to reproduce this, you can use the example `seg` model found in the repo for your demo project.

In addition:
> 1-model is standard segmentation model

Doesn't answer what I asked.

**Comment by areytechai** [comment] 2024-10-27 11:49
> > 1-model is standard segmentation model

can you explain detailly?

**Comment by kbank14** [comment] 2024-10-30 01:25
i can't speak english. (영어를 못해요)

var val = CreateOrtValue(...);

val.Dispose()  <-- need dispose

using var ortValue = CreateOrtValue(...);    <-- need using 

ortValue  <-- auto dispose


CreateOrtValue() 를 사용하는 모든 것에 using을 사용하거나 dispose를 해줘야 메모리 릭이 발생 안함.


onnx 사용 가이드에 아래와 같이 설명이 있음
using var ort = OrtValue.CreateTensorValueFromMemory(...).

**Comment by areytechai** [comment] 2024-10-31 20:45
> i can't speak english. (영어를 못해요)
> 
> var val = CreateOrtValue(...);
> 
> val.Dispose() <-- need dispose
> 
> using var ortValue = CreateOrtValue(...); <-- need using
> 
> ortValue <-- auto dispose
> 
> CreateOrtValue() 를 사용하는 모든 것에 using을 사용하거나 dispose를 해줘야 메모리 릭이 발생 안함.
> 
> onnx 사용 가이드에 아래와 같이 설명이 있음 using var ort = OrtValue.CreateTensorValueFromMemory(...).

can you share full code please?

@dme-compunet  is this fix problem?

**Comment by dme-compunet** [comment] 2024-11-01 11:06
I don’t think `Dispose` is important here, and in any case, it’s called in the deconstructor by the GC.

@areytechai to solve your issue, you first need to check if there’s actually a problem. If you are able create a minimal project that reproduces the memory leak, I can continue from there; otherwise, I see this issue as closed.

**Closed** 2024-11-19 19:15 UTC
